name: Build and deploy to GitHub Pages

on:
  workflow_dispatch:

jobs:
  BuildEleventy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'node'
          check-latest: true

      - name: Install dependencies & build
        run: |
          npm install
          npm run build          

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}